title: Cynthia Tia # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Planner at Niagara Region
  <br><br>
  I'm an urban planner driven by a deep passion for policymaking, climate change strategies, and sustainable development. My work revolves around creating cities that are economically vibrant while also prioritizing environmental resilience and social equity.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
